compose/dashboard/urls.py
# Django
from django.urls import path

# Local
from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
]

compose/movies/urls.py
# Django
from django.urls import path

# Local
from .views import MovieFinderFormView
from .views import MovieListView
from .views import add_to_favourites

urlpatterns = [
    path('find_movies/', MovieFinderFormView.as_view(), name='find_movies'),
    path('movies_list/', MovieListView.as_view(), name='movies_list'),
    path('add_to_favourites/', add_to_favourites, name='add_to_favourites'),
]

compose/project/urls.py
# Django
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('', include(('movies.urls', 'movies'), namespace='movies')),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('accounts/', include('allauth.urls')),
]

compose/users/urls.py
# Django
from django.urls import path

# Local
from .views import UserDetailView

urlpatterns = [
    path('profile/', UserDetailView.as_view(), name='profile'),
]

compose/movies/models.py
# Django
from django.db import models


class Movie(models.Model):

    title = models.CharField(
        'Title',
        max_length=255,
    )
    year = models.CharField(
        'Release date',
        blank=True,
        null=True,
        max_length=9,
    )
    imdb_id = models.CharField(
        'IMDB id',
        blank=True,
        null=True,
        max_length=20,
    )
    kind = models.CharField(
        'Type',
        blank=True,
        null=True,
        max_length=50,
    )
    poster_url = models.URLField(
        'Poster url',
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.title

compose/users/models.py
# Django
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):

    last_visit = models.DateTimeField(
        'Last visit',
        blank=True,
        null=True,
    )

    favourite_movies = models.ManyToManyField(
        'movies.Movie',
        verbose_name='Favourite movies',
    )

    class Meta:  # noqa: D106

        verbose_name = 'User'
        verbose_name_plural = 'Users'

compose/movies/forms.py
# Django
from django import forms

# Project
from movies.models import Movie


class MovieFindForm(forms.ModelForm):

    title = forms.CharField(
        label='title',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mr-sm-2',
                'placeholder': 'title',
            }),
    )
    year = forms.CharField(
        label='year',
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mr-sm-2',
                'placeholder': 'year',
            }),
    )

    class Meta:
        model = Movie
        fields = ['title', 'year']

compose/accounts/views.py
# Django
from django.shortcuts import render

# Create your views here.

compose/dashboard/views.py
# Django
from django.views.generic import TemplateView


class HomeView(TemplateView):

    template_name = 'dashboard/home_view.html'

compose/movies/views.py
# Standard Library
import math

# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views.generic import FormView
from django.views.generic import ListView

# Local
from .forms import MovieFindForm
from .models import Movie
from .utils import create_movies
from .utils import create_url_params
from .utils import get_data_from_api


class MovieFinderFormView(LoginRequiredMixin, FormView):

    template_name = 'movies/search_form.html'
    form_class = MovieFindForm


def get_options(page_no, pages):
    if page_no == 1 and pages < 4:
        return [i for i in range(1, pages)]
    elif page_no == 1 and pages > 3:
        return [i for i in range(1, 4)]
    elif page_no == pages:
        return [i for i in range(pages+1)][-3:]
    else:
        return [page_no - 1, page_no, page_no + 1]


class MovieListView(LoginRequiredMixin, ListView):
    template_name = 'movies/list.html'

    def get_queryset(self):
        params, self.page_no = create_url_params(self.request)
        api_url = f'http://www.omdbapi.com/?{params}apikey=60110a3f'
        self.movies, self.results = get_data_from_api(api_url)
        return self.movies

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['movies'] = self.movies
        context['results'] = self.results
        context['current_page'] = self.page_no
        if self.results:
            context['pages_no'] = math.ceil(int(self.results)/10)
            context['page_options'] = get_options(self.page_no, context['pages_no'])
            create_movies(self.movies)
        return context


def add_to_favourites(request):
    imdb_id = request.GET.get('movie_id')
    user = request.user
    movie = Movie.objects.get(imdb_id=imdb_id)
    result = False
    if movie not in user.favourite_movies.all():
        user.favourite_movies.add(movie)
        result = True
    return JsonResponse({'added': result})

compose/users/views.py
# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class UserDetailView(LoginRequiredMixin, TemplateView):

    template_name = 'users/profile.html'

compose/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Movie DB</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">
</head>
<body>
{% include 'bootstrap_navbar.html' %}
<div class="container-fluid text-center">
  <div class="row content">
    {% include 'bootstrap_left_sidenav.html' %}
    <div class="col-sm-8 text-left">
      <div class="pt-3">
        {% block content %}
        {% endblock %}
      </div>
    </div>
    {% include 'bootstrap_right_sidenav.html' %}
  </div>
</div>

<!-- JS -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/my_js.js' %}"></script>

<!-- Ajax urls -->
<script>const addToFavourites = "{% url 'movies:add_to_favourites' %}"</script>
</body>
</html>

compose/templates/bootstrap_left_sidenav.html
<div class="col-2">
    <div class="col-12 sidenav">
      {% if not request.user.is_anonymous %}
      <p><a href="{% url 'movies:find_movies' %}">Find movie!</a></p>
      <p><a href="{% url 'users:profile' %}">Your profile</a></p>
      <p><a href="{% url 'account_logout' %}">Sign out</a></p>
      {% else %}
      <p><a href="{% url 'account_login' %}">Sign in</a></p>
      <p><a href="{% url 'account_signup' %}">Sign up</a></p>
      {% endif %}
    </div>
</div>

compose/templates/bootstrap_navbar.html
<nav class="navbar navbar-light bg-info justify-content-between">
  <a class="navbar-brand">Movie DB (<small>Created by Szymon Bugaj</small>)</a>
</nav>

compose/templates/bootstrap_pagination.html
<div class="container">
  <ul class="pagination">


    <form method="get" enctype="multipart/form-data" action="{% url 'movies:movies_list' %}">
      <li class="page-item {% if current_page == 1 %}disabled {% endif %}"><button class="page-link" type="submit">
        First<input type="hidden" name="page" value="1">
        <input type="hidden" name="title" value="{{ request.GET.title }}">
        <input type="hidden" name="year" value="{{ request.GET.year }}">
      </button></li>
    </form>

    {% for option in page_options %}
      <form method="get" enctype="multipart/form-data" action="{% url 'movies:movies_list' %}">
        <li class="page-item {% if current_page == option %}disabled {% endif %}"><button class="page-link" type="submit">
          {{ option }}<input type="hidden" name="page" value="{{ option }}">
          <input type="hidden" name="title" value="{{ request.GET.title }}">
          <input type="hidden" name="year" value="{{ request.GET.year }}">
        </button></li>
      </form>
    {% endfor %}

    <form method="get" enctype="multipart/form-data" action="{% url 'movies:movies_list' %}">
      <li class="page-item {% if current_page == pages_no %}disabled {% endif %}"><button class="page-link" type="submit">
        Last<input type="hidden" name="page" value="{{ pages_no }}">
        <input type="hidden" name="title" value="{{ request.GET.title }}">
        <input type="hidden" name="year" value="{{ request.GET.year }}">
      </button></li>
    </form>
  </ul>
</div>

compose/templates/bootstrap_right_sidenav.html
<div class="col-2">
    <div class="col-12 sidenav">
</div>
</div>

compose/templates/dashboard/home_view.html
{% extends 'base.html' %}

{% block content %}
  <h2>Home View</h2>
{% endblock %}

compose/templates/movies/list.html
{% extends 'base.html' %}
{% block content %}
  {% if results %}
    <table class="table">
      {% for movie in movies %}
        {% if forloop.first %}
          <thead>
          {% for param in movie.keys %}
            <th scope="col">{{ param }}</th>
          {% endfor %}
          <th scope="col">add to favourites</th>
          </thead>
        {% endif %}
        <tbody>
        <tr>
          {% for param, value in movie.items %}
            <td>
              {% if param == 'Poster' %}
                {% if value %}
                  <img src="{{ value }}" height="100">
                {% else %}
                  <p>There is no poster. :( </p>
                {% endif %}
              {% else %}
                {{ value }}
              {% endif %}
            </td>
          {% endfor %}
          <td><input type="button" class="btn btn-primary" value="Add to favorites!" id="fav_button_{{ movie.imdbID }}"></td>
        </tr>
      {% endfor %}
    </tbody>
    </table>
    <p>All results: {{ results }}</p>

    {% include 'bootstrap_pagination.html' %}
  {% else %}
    {{ movies }}
  {% endif %}
{% endblock %}

compose/templates/movies/movies.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" action="{% url 'movies:get_movies_from_api' %}">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Search!">
  </form>
{% endblock %}

compose/templates/movies/search_form.html
{% extends 'base.html' %}

{% block content %}
  <form class="form-inline" method="get" enctype="multipart/form-data" action="{% url 'movies:movies_list' %}">
    <label for="id_{{ form.title.name }}"></label>
    {{ form.title }}
    <span class="text-danger text-left">{{ form.title.errors }}</span>
    <label for="id_{{ form.year.name }}"></label>
    {{ form.year }}
    <span class="text-danger text-left">{{ form.year.errors }}</span>
    <input type="hidden" name="page" value="1">
    <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
  </form>
{% endblock %}

compose/templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

compose/templates/users/profile.html
{% extends 'base.html' %}
{% block content %}
  {% if request.user.first_name %}<p><b>first name:</b> {{ request.user.first_name }}</p>{% endif %}
  {% if request.user.last_name %}<p><b>last name:</b> {{ request.user.last_name }}</p>{% endif %}
  {% if request.user.username %}<p><b>login:</b> {{ request.user.username }}</p>{% endif %}
  {% if request.user.email %}<p><b>email:</b> {{ request.user.email }}</p>{% endif %}
  <p><b>favorites movies:</b></p>
  {% for movie in request.user.favourite_movies.all %}
    <ul>
      <li>{{ movie }}</li>
    </ul>
  {% endfor %}
{% endblock %}